<form id="highlight" style="float:right">
  <p>\$("# 
        <input type="text" name="selector" id="selector"/>
      ").load(
        <input type="text" name="url" id="url"/>
       ,
        <input type="text" name="params" id="params"/>
       )
        <input type="button" name="load" value="load" id="load"/>
   </p>
   <pre><code id="load-code">

   </code></pre>
</form>


<h1>Ajax Demo</h1>

<p id="response">[Load responses here]</p>

