<style>
#highlight input {
  font-size: 150%;
  display: block;
  margin-bottom: 1em;
}
#target {
  font-size: 200%;
  width: 25em;
}
</style>

<form id="highlight" style="float:right">
  <input type="button" value="show" class="call-value"/>
  <input type="button" value="hide" class="call-value"/>
  <input type="button" value="toggle" class="call-value"/>

  <input type="button" value="show('normal')" class="eval-value"/>
  <input type="button" value="hide('slow')" class="eval-value"/>
  <input type="button" value="toggle('fast')" class="eval-value"/>

  <input type="button" value="fadeIn('normal')" class="eval-value"/>
  <input type="button" value="fadeOut('normal')" class="eval-value"/>

  <input type="button" value="slideDown(3000)" class="eval-value"/>
  <input type="button" value="slideUp(1000)" class="eval-value"/>

</form>


<h1>Effects Demo</h1>

<p id="target">No person shall be held to answer for any capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury, except in cases arising in the land or naval forces, or in the Militia, when in actual service in time of War or public danger; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation.</p>


