<form id="sandbox">
  <p>
    <label for="code">Code:</label><br/>
    <textarea rows="5" cols="73" name="code" id="code">
    </textarea>
  </p>
  <p>
  <p>
    <input type="submit" value="Formatted!" id="formatted"/>
    <input type="submit" value="Unformatted!" id="unformatted"/>
  </p>
</form>

<pre style="font-size:150%;"><code class="js-shell">
<span class="input" id="input">&nbsp;</span>
<span class="output"id="output">&nbsp;</span>
</code></pre>

