<form id="highlight" style="float:right">
  <label for="selector">Selector:</label>
  <input type="text" name="selector" id ="selector"/>
  <input type="submit" value="Highlight it!"/>
</form>

<h1>Selectors Demo</h1>

<div id="section-1">
  <p id="p1" class="vivid leader">Paragraph 1</p>
  <p id="p2">Paragraph 2</p>
  <p id="p3" class="honorificabilitudinitatibus">Paragraph 3 has a <span>nested span</span></p>
  <p id="p4" class="vivid">Paragraph 4</p>
  <p id="p5">Paragraph 5 has a <span>doubly <span> nested span</span> </span></p>
  <div>This is not a paragraph</div>
</div>

