<html>
  <head>
    <script src="/javascripts/jquery-1.3.2.js" type="text/javascript"></script>
    <script src="/javascripts/jquery.color.js" type="text/javascript"></script>
    <script src="/javascripts/code-highlighter.js" type="text/javascript"></script>
    <script src="/javascripts/languages.js" type="text/javascript"></script>
    <script src="/javascripts/application.js" type="text/javascript"></script>
    <script src="/javascripts/$content$.js" type="text/javascript"></script>
    <link href="/stylesheets/code-highlighter.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/stylesheets/screen.css" media="screen" rel="stylesheet" type="text/css" />
  </head>
  <body>
    $(content)()$
    <div id="log">&nbsp;</div>
  </body>
</html>

