#!/bin/sh
export LIKESTREAM_ENV=development
CLASSPATH=src:templates:config

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

java -cp $CLASSPATH clojure.lang.Script src/demos/jquery/server.clj